modLoader = "javafml"
loaderVersion = "[${forge},)"
issueTrackerURL = "https://github.com/rhysdh540/create-hacks/issues"
license = "GPL-3.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "ardhitilts"
authors = "rdh"
description = '''
Do you or a loved one suffer from ardhitilts?
'''
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId="create"
mandatory=true
versionRange="${create_forge}"
ordering="NONE"
side="BOTH"